INSERT INTO devops (id ,name , dag, task_group,type) VALUES 
(10,	"COMPASS LONG BIASED FUNDO DE INVESTIMENTO EM COTAS DE FUNDOS DE INVESTIMENTO MULTIMERCADO","email_cotas_pl",	"external-email-subset-funds",	"funds"),
(17,	"COMPASS ESG CREDIT SELECTION FIC DE FI RENDA FIXA CREDITO PRIVADO LONGO PRAZO","email_cotas_pl",	"external-email-subset-funds",	"funds"),
(3,	"COMPASS NINETY ONE GLOBAL FRANCHISE FUNDO DE INVESTIMENTO EM COTAS DE FUNDO DE INVESTIMENTO EM ACOES INVESTIMENTO NO EXTERIOR","email_cotas_pl",	"external-email-subset-funds",	"funds"),
(30,	"COMPASS YIELD 30 FUNDO DE INVESTIMENTO RENDA FIXA CREDITO PRIVADO LONGO PRAZO","email_cotas_pl",	"external-email-subset-funds",	"funds"),
(32,	"COMPASS NINETY ONE GLOBAL FRANCHISE BRL FUNDO DE INVESTIMENTO EM COTAS DE FUNDO DE INVESTIMENTO EM ACOES INVESTIMENTO NO EXTERIOR","email_cotas_pl",	"external-email-subset-funds",	"funds"),
(42,	"COMPASS PREVIDENCIA FIFE FUNDO DE INVESTIMENTO MULTIMERCADO CREDITO PRIVADO LONGO PRAZO","email_cotas_pl",	"external-email-subset-funds",	"funds"),
(49,	"COMPASS HIGH YIELD 180 ADVISORY FIC FIM CP","email_cotas_pl",	"external-email-subset-funds",	"funds"),
(1,	"CDI","email_cotas_pl",	"external-email-subset-funds",	"indexes"),
(26,	"PTAX REF 2 DIAS","email_cotas_pl",	"external-email-subset-funds",	"indexes"),
(70,	"IBOVESPA","email_cotas_pl",	"external-email-subset-funds",	"indexes"),
(102,	"IMA_B","email_cotas_pl",	"external-email-subset-funds",	"indexes"),
(1011,	"IPCA + YIELD IMA-B","email_cotas_pl",	"external-email-subset-funds",	"indexes"),
(10,	"COMPASS LONG BIASED FUNDO DE INVESTIMENTO EM COTAS DE FUNDOS DE INVESTIMENTO MULTIMERCADO"	,"prev_email_cotas_pl"	,"prev_email_cotas_pl"	,"funds"),
(17,	"COMPASS ESG CREDIT SELECTION FIC DE FI RENDA FIXA CREDITO PRIVADO LONGO PRAZO"	,"prev_email_cotas_pl"	,"prev_email_cotas_pl"	,"funds"),
(3,	"COMPASS NINETY ONE GLOBAL FRANCHISE FUNDO DE INVESTIMENTO EM COTAS DE FUNDO DE INVESTIMENTO EM ACOES INVESTIMENTO NO EXTERIOR"	,"prev_email_cotas_pl"	,"prev_email_cotas_pl"	,"funds"),
(30,	"COMPASS YIELD 30 FUNDO DE INVESTIMENTO RENDA FIXA CREDITO PRIVADO LONGO PRAZO"	,"prev_email_cotas_pl"	,"prev_email_cotas_pl"	,"funds"),
(32,	"COMPASS NINETY ONE GLOBAL FRANCHISE BRL FUNDO DE INVESTIMENTO EM COTAS DE FUNDO DE INVESTIMENTO EM ACOES INVESTIMENTO NO EXTERIOR"	,"prev_email_cotas_pl"	,"prev_email_cotas_pl"	,"funds"),
(42,	"COMPASS PREVIDENCIA FIFE FUNDO DE INVESTIMENTO MULTIMERCADO CREDITO PRIVADO LONGO PRAZO"	,"prev_email_cotas_pl"	,"prev_email_cotas_pl"	,"funds"),
(14,	"COMPASS ESG CREDIT SELECTION FUNDO DE INVESTIMENTO RENDA FIXA CREDITO PRIVADO LONGO PRAZO"	,"prev_email_cotas_pl"	,"prev_email_cotas_pl"	,"funds"),
(2,	"COMPASS NINETY ONE GLOBAL FRANCHISE FUNDO DE INVESTIMENTO EM ACOES INVESTIMENTO NO EXTERIOR"	,"prev_email_cotas_pl"	,"prev_email_cotas_pl"	,"funds"),
(31,	"COMPASS NINETY ONE GLOBAL FRANCHISE BRL FUNDO DE INVESTIMENTO EM ACOES INVESTIMENTO NO EXTERIOR"	,"prev_email_cotas_pl"	,"prev_email_cotas_pl"	,"funds"),
(35,	"FCOPEL FUNDO DE INVESTIMENTO MULTIMERCADO INVESTIMENTO NO EXTERIOR III"	,"prev_email_cotas_pl"	,"prev_email_cotas_pl"	,"funds"),
(43,	"COMPASS LCDA MASTER FI MULT IE CRED PRIV"	,"prev_email_cotas_pl"	,"prev_email_cotas_pl"	,"funds"),
(9,	"COMPASS LONG BIASED FUNDO DE INVESTIMENTO MULTIMERCADO"	,"prev_email_cotas_pl"	,"prev_email_cotas_pl"	,"funds"),
(1,	"CDI"	,"prev_email_cotas_pl"	,"prev_email_cotas_pl"	,"indexes"),
(26,	"PTAX REF 2 DIAS"	,"prev_email_cotas_pl"	,"prev_email_cotas_pl"	,"indexes"),
(70,	"IBOVESPA"	,"prev_email_cotas_pl"	,"prev_email_cotas_pl"	,"indexes"),
(102,	"IMA_B"	,"prev_email_cotas_pl"	,"prev_email_cotas_pl"	,"indexes"),
(1011,	"IPCA + YIELD IMA-B"	,"prev_email_cotas_pl"	,"prev_email_cotas_pl"	,"indexes")